### ISSUE TITLE
Water glitching out.

### ISSUE THREAD

**Issue by Rusted-Cognition** [DrDesten/DrDestens_McShader#2] opened 2021-09-04 04:38 UTC
Hi, I just downloaded your shader and I am very impressed with how it looks and performs but for some reason the water is glitching out. Is ther a way to fix this or maybe just turn the water effects off? Thanks, -Rusted_Cognition

![2021-09-04_14 24 27](https://user-images.githubusercontent.com/90081341/132082566-f290b99e-cbc1-46e6-a790-0e4960bbfd03.png)
![2021-09-04_14 24 04](https://user-images.githubusercontent.com/90081341/132082558-5d324b5b-0f6b-4a04-82f0-66b21f7a11ac.png)
![2021-09-04_14 22 54](https://user-images.githubusercontent.com/90081341/132082538-48c49eaf-3f8a-433e-a292-0cb223e99a37.png)
![2021-09-04_14 23 05](https://user-images.githubusercontent.com/90081341/132082541-579780b8-a058-4e1a-be07-393a12fe367d.png)
![2021-09-04_14 23 51](https://user-images.githubusercontent.com/90081341/132082545-fc4cbaa8-c5ca-4a7c-8139-bc3e590df226.png)
![2021-09-04_14 24 01](https://user-images.githubusercontent.com/90081341/132082547-289c2162-edb8-48fd-8c8a-3198b3092740.png)

**Comment by Rusted-Cognition** [comment] 2021-09-04 05:58
I would love to use these shaders in my Youtube videos but with the water like this I can't. I would be happy even if the water was just default vanilla (maybe with reflections). I just can't seem to fix it.

**Comment by DrDesten** [comment] 2021-09-04 08:54
I've seen a similar bug before...
 - what graphics card do you have?
 - OS?
 - are you using the newest optifine version?
 - What mc version is this?

I would need that in order to reproduce this bug

**Comment by Rusted-Cognition** [comment] 2021-09-04 09:57
Yeah I understand if it dosen't work as I am on an M1 mac (can't affor a PC atm). So I'm on macOS. Yes I am using the latest optifine. And I am using Minecraft 1.17.1.

**Comment by Rusted-Cognition** [comment] 2021-09-04 09:57
(Integrated Graphics)

**Comment by DrDesten** [comment] 2021-09-04 12:21
Since you are on a Mac, first I am surprised it works as well as it does tbh.
But I cannot offer support for Mac's, I am sorry. 
The prominent issue seems to be bump mapping on water, you could turn the bump strength down in the "water" section of the menu.
It can't go to zero at the moment, but maybe 0.2 is enough? I'll definitely change to be able to go 0.0 though.
Still, try setting it to 0.2 and see what happens.

**Comment by Rusted-Cognition** [comment] 2021-09-04 13:36
Yeah, It works almost without any issues at like 60fps. I have tried turning it down all they way but then I gives me other weird problems like in the last screenshot where the water seems just stop rendering in at all. Anyway thanks for responding! I'll just have to save and get a PC lol.

**Comment by DrDesten** [comment] 2021-09-04 13:50
I will add an option to disable bump mapping on water.  Look out for the next release

**Comment by DrDesten** [comment] 2021-09-04 22:25
For now you can try this version (it's the preview for the next version)
It lets you disable Bump Mapping on water.

**It should be below:**
[DrDestens MinecraftShaders v1.3.2 Preview.zip](https://github.com/DrDesten/DrDestens_McShader/files/7110593/DrDestens.MinecraftShaders.v1.3.2.Preview.zip)

**Comment by Rusted-Cognition** [comment] 2021-09-05 00:41
Thank you! Just a question: how hard would it be to make a setting to enable the vanilla water texture a bit like the Builders QOL shaders? Then if I have all the settings off on your shader besides the reflection there are no problems! I don't expect you to  do this I just thought that if is wasn't too difficult then it may be worth asking! The Builders QOL shader works on my computer without any issues but I like yours way more!
![2021-09-05_10 37 03](https://user-images.githubusercontent.com/90081341/132111281-55e6fa66-5e2c-44e0-9364-ec84109fcb09.png)
<img width="1440" alt="Screen Shot 2021-09-05 at 10 37 19 am" src="https://user-images.githubusercontent.com/90081341/132111276-39414321-238e-4c12-88f6-39d1a14a56b7.png">

**Comment by Rusted-Cognition** [comment] 2021-09-05 00:52
The preview version is much better, It resolves some of the issues! The main problem now is the reflections and where the water meets the land... Is there a way to disable reflections for the water and only have the sun shine on it like on the Builders QOL? The water as a whole looks better but I am getting these glitched edges and reflections. The main reason I want this shader is because of the Specular mapping! Thanks for your help.
![Screen Shot 2021-09-05 at 10 45 17 am (2)](https://user-images.githubusercontent.com/90081341/132111452-9920b61d-87a4-4496-9ab6-312b5108eb19.png)
![Screen Shot 2021-09-05 at 10 53 36 am (2)](https://user-images.githubusercontent.com/90081341/132111485-65444b88-c373-4b26-b87a-5169c8ace8b3.png)

**Comment by DrDesten** [comment] 2021-09-05 02:56
You can change the reflection to "Cubemap-like" in the menu. It doesn't have these edges. (Click on "Raytraced" in the Screen Space Reflection section)
As for the vanilla texture, it's not that difficult to add back. I might do it.

**Comment by Rusted-Cognition** [comment] 2021-09-05 03:10
Thanks so much!

**Comment by DrDesten** [comment] 2021-09-05 07:10
You should be able to bring back the water texture with this version:
[DrDestens MinecraftShaders v1.3.2 Preview 2.zip](https://github.com/DrDesten/DrDestens_McShader/files/7111090/DrDestens.MinecraftShaders.v1.3.2.Preview.2.zip)

Is the shader in a usable state now?
Then I'll close the issue.

**Closed as completed** 2021-09-08 15:53 UTC
